# Generated by Django 3.2.7 on 2021-09-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='targrt',
            new_name='target',
        ),
    ]
